spring:
  application:
    name: stock-price
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: finance_user
    password: 123456
    driverClassName: org.postgresql.Driver
    hikari:
      schema: public